-- UNO game history schema (H2-compatible)
-- Hibernate auto-creates/updates tables; this script documents the model.

CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    winner_id BIGINT NOT NULL REFERENCES players(id),
    rounds_played INT NOT NULL
);

CREATE TABLE IF NOT EXISTS rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id),
    round_number INT NOT NULL,
    winner_id BIGINT NOT NULL REFERENCES players(id),
    points_scored INT NOT NULL,
    completed_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS game_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(id),
    player_id BIGINT NOT NULL REFERENCES players(id),
    score INT NOT NULL,
    CONSTRAINT uq_game_player UNIQUE (game_id, player_id)
);
